import COLORS from './colors';

export default [
  COLORS.BLUE,
  COLORS.ORANGE,
  COLORS.BRIGHT_YELLOW,
  COLORS.TAN,
  COLORS.GREY,
  COLORS.MEDIUM_YELLOW,
  COLORS.BEIGE,
  COLORS.DARK_GREY,
  COLORS.RED,
  COLORS.GREEN,
];
